spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: backend
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:9999/realms/MYBANKAPP